# Generated by Django 4.1.5 on 2023-02-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=1000)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('artist_name', models.CharField(max_length=500)),
                ('release_date', models.DateTimeField(verbose_name='date released')),
                ('genre', models.CharField(max_length=100)),
                ('itunes_id', models.IntegerField(default=0)),
                ('artwork_url', models.CharField(default=None, max_length=300)),
                ('album_type', models.CharField(default='Album', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=500)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('genre', models.CharField(max_length=100)),
                ('itunes_id', models.IntegerField(default=0)),
                ('amg_id', models.IntegerField(default=0)),
                ('genre_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=1000)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(max_length=1000)),
                ('release_date', models.DateTimeField(verbose_name='date released')),
                ('genre', models.CharField(max_length=100)),
                ('track_time', models.CharField(default=None, max_length=40)),
                ('itunes_id', models.IntegerField(default=0)),
                ('artwork_url', models.CharField(default=None, max_length=300)),
                ('explicit', models.CharField(blank=True, max_length=100, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.artist')),
            ],
        ),
        migrations.CreateModel(
            name='PFReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=1000)),
                ('artist_name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('author', models.CharField(default=None, max_length=500)),
                ('abstract', models.CharField(default=None, max_length=1500)),
                ('editorial', models.CharField(default=None, max_length=25000)),
                ('bnm', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.album')),
            ],
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.CharField(max_length=300)),
                ('embed_type', models.CharField(max_length=100)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.artist'),
        ),
    ]
