# Generated by Django 4.1.5 on 2023-01-30 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=1000)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('artist_name', models.CharField(max_length=500)),
                ('release_date', models.DateTimeField(verbose_name='date released')),
                ('genre', models.CharField(max_length=100)),
                ('itunes_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=500)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('genre', models.CharField(max_length=100)),
                ('itunes_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=1000)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(max_length=1000)),
                ('release_date', models.DateTimeField(verbose_name='date released')),
                ('genre', models.CharField(max_length=100)),
                ('track_time', models.IntegerField(default=0)),
                ('itunes_id', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.artist'),
        ),
    ]
