# Generated by Django 4.1.5 on 2023-02-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='explicit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
