# Generated by Django 4.1.5 on 2023-02-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfreview',
            name='bnm',
            field=models.BooleanField(default=False),
        ),
    ]
