# Generated by Django 4.1.5 on 2023-01-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artwork_url',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='artist',
            name='amg_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='artwork_url',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='song',
            name='explicit',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
