# Generated by Django 4.1.5 on 2023-02-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0002_pfreview_bnm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PFReview',
        ),
    ]
