# Generated by Django 4.1.5 on 2023-01-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0002_album_artwork_url_artist_amg_id_artist_genre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(default='Album', max_length=100),
        ),
    ]
