# Generated by Django 3.2.16 on 2023-02-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0003_wikiblurb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='amg_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='artist',
            name='artwork_url',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
