# Generated by Django 4.1.5 on 2023-02-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0003_delete_pfreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=1000)),
                ('artist_name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('author', models.CharField(default=None, max_length=500)),
                ('abstract', models.CharField(default=None, max_length=1500)),
                ('editorial', models.CharField(default=None, max_length=25000)),
                ('bnm', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sethtunes.album')),
            ],
        ),
    ]
