# Generated by Django 4.1.5 on 2023-01-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0003_album_album_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_time',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
