# Generated by Django 4.1.5 on 2023-01-31 03:00

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0004_alter_song_track_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
