# Generated by Django 4.1.5 on 2023-01-31 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='song',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sethtunes.song'),
        ),
    ]
