# Generated by Django 4.1.5 on 2023-01-31 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sethtunes', '0006_video_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
